// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  var Posn, allPlates, allQuestions, canvas, ctx, currentScore, draw, drawCenter, gameEnd, isCorrect, keysDown, lastKeys, leftStop, left_answers, left_correct, loadContent, loadGerman, loadJapanese, loadPlates, loadSpanish, madFace, newPress, questionsToAsk, rightStop, right_answers, right_correct, shuffle, slidingPlates, thisKeys, update, winning;

  canvas = null;

  ctx = null;

  keysDown = [];

  Posn = (function() {
    function Posn(x, y) {
      this.x = x;
      this.y = y;
    }

    return Posn;

  })();


  /*
   */

  leftStop = false;

  rightStop = false;

  currentScore = 0;

  winning = false;

  gameEnd = false;

  left_correct = null;

  right_correct = null;

  left_answers = [];

  right_answers = [];

  allPlates = [new Plate(220, 30, -0.75, 2.25, 30, 220, null), new Plate(265, -120, -0.75, 2.25, 30, 220, null), new Plate(315, -270, -0.75, 2.25, 30, 220, null), new Plate(370, -420, -0.75, 2.25, 30, 220, null), new Plate(540, 30, 0.4, 2.25, 30, 540, null), new Plate(520, -120, 0.4, 2.25, 30, 540, null), new Plate(500, -270, 0.4, 2.25, 30, 540, null), new Plate(480, -420, 0.4, 2.25, 30, 540, null)];

  loadContent = function() {};

  loadSpanish = function() {};

  loadJapanese = function() {};

  loadGerman = function() {};

  newPress = function(key) {
    return thisKeys[key] && !lastKeys[key];
  };

  allQuestions = [];

  questionsToAsk = [];

  loadPlates = function() {};

  shuffle = function(list) {
    var k, n, _ref, _results;
    n = list.length;
    _results = [];
    while (n > 1) {
      n--;
      k = Math.floor(Math.random() * (n + 1));
      _results.push((_ref = [list[n], list[k]], list[k] = _ref[0], list[n] = _ref[1], _ref));
    }
    return _results;
  };

  update = function() {
    var i, lastKeys, madFace, slidingAfter, slidingBefore, slidingPlates, thisKeys, _i, _ref;
    lastKeys = thisKeys;
    thisKeys = keysDown.slice(0);
    if (newPress(39)) {
      rightStop = !rightStop;
    }
    if (newPress(37)) {
      leftStop = !leftStop;
    }
    for (i = _i = 0, _ref = allPlates.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
      if ((!leftStop && i < 4) || (!rightStop && i >= 4)) {
        slidingBefore = slidingPlates > 0;
        slidingPlates = allPlates[i].updatePlates(slidingPlates);
        slidingAfter = slidingPlates > 0;
        if (slidingBefore && slidingAfter) {
          loadPlates();
        }
      }
    }
    if (leftStop && rightStop && !gameEnd) {
      winning = isCorrect();
      if (winning) {
        currentScore += 200;
        slidingPlates = 8;
        madFace = 0;
      } else {
        currentScore -= 100;
        madFace++;
      }
      leftStop = false;
      rightStop = false;
    }
    winning = isCorrect() && leftStop && rightStop;
    if (winning) {
      return currentScore += 200;
    }
  };

  slidingPlates = 0;

  madFace = 0;

  isCorrect = function() {
    var gotLeft, gotRight, p, _i, _j, _len, _len1, _ref, _ref1;
    gotLeft = false;
    gotRight = false;
    _ref = allPlates.slice(0, 4);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      p = _ref[_i];
      if (p.in_zone && p.plateContents === left_correct) {
        gotLeft = true;
      }
    }
    _ref1 = allPlates.slice(4, 8);
    for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
      p = _ref1[_j];
      if (p.in_zone && p.plateContents === right_correct) {
        gotRight = true;
      }
    }
    return gotLeft && gotRight;
  };

  lastKeys = [];

  thisKeys = [];

  drawCenter = function(img, posn, color) {};

  draw = function() {};


  /*
   */

  window.requestAnimFrame = window.requestAnimationFrame || window.webkitRequestAnimationFrame || window.mozRequestAnimationFrame || window.oRequestAnimationFrame || window.msRequestAnimationFrame || function(callback) {
    return window.setTimeout(callback, 1000 / 60);
  };

  $(document).ready(function() {
    var animloop;
    canvas = $('#canvas')[0];
    ctx = canvas.getContext('2d');
    $(document).keydown(function(evt) {
      return keysDown[evt.which] = true;
    });
    $(document).keyup(function(evt) {
      return delete keysDown[evt.which];
    });
    return (animloop = function() {
      requestAnimFrame(animloop);
      update();
      draw();
      return null;
    })();
  });

}).call(this);
