// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  var Question;

  Question = (function() {
    function Question(basename) {
      this.basename = basename;
    }

    Question.prototype.load = function(callback) {
      var i, loader;
      loader = new Loader;
      this.question = loader.image("" + this.basename + "q.jpg");
      this.left_answer = loader.image("" + this.basename + "a.jpg");
      this.right_answer = loader.image("" + this.basename + "p.jpg");
      this.left_duds = (function() {
        var _i, _results;
        _results = [];
        for (i = _i = 1; _i <= 3; i = ++_i) {
          _results.push(loader.image("" + this.basename + "d" + i + ".jpg"));
        }
        return _results;
      }).call(this);
      return loader.afterLoad(callback);
    };

    return Question;

  })();

  window.Question = Question;

}).call(this);
