// Generated by CoffeeScript 1.7.1
(function() {
  var Question, afterAll, contentLoad;

  contentLoad = function(url) {
    var events, img, loaded;
    img = new Image();
    loaded = false;
    events = [];
    $(img).load(function() {
      var evt, _i, _len, _results;
      loaded = true;
      _results = [];
      for (_i = 0, _len = events.length; _i < _len; _i++) {
        evt = events[_i];
        _results.push(evt());
      }
      return _results;
    });
    img.src = url;
    return [
      img, function(evt) {
        if (loaded) {
          return evt();
        } else {
          return events.push(evt);
        }
      }
    ];
  };

  afterAll = function(events, callback) {
    var decrement, evt, remaining, _i, _len, _results;
    remaining = events.length;
    decrement = function() {
      remaining -= 1;
      if (remaining === 0) {
        return callback();
      }
    };
    _results = [];
    for (_i = 0, _len = events.length; _i < _len; _i++) {
      evt = events[_i];
      _results.push(evt(decrement));
    }
    return _results;
  };

  Question = (function() {
    function Question(basename) {
      this.basename = basename;
    }

    Question.prototype.load = function(callback) {
      var dud, e0, e1, e2, events, evt, i, _i, _ref, _ref1, _ref2, _ref3;
      _ref = contentLoad("" + this.basename + "q.jpg"), this.question = _ref[0], e0 = _ref[1];
      _ref1 = contentLoad("" + this.basename + "a.jpg"), this.left_answer = _ref1[0], e1 = _ref1[1];
      _ref2 = contentLoad("" + this.basename + "p.jpg"), this.right_answer = _ref2[0], e2 = _ref2[1];
      events = [e0, e1, e2];
      this.left_duds = [];
      for (i = _i = 1; _i <= 3; i = ++_i) {
        _ref3 = contentLoad("" + this.basename + "d" + i + ".jpg"), dud = _ref3[0], evt = _ref3[1];
        this.left_duds.push(dud);
        events.push(evt);
      }
      return afterAll(events, callback);
    };

    return Question;

  })();

  window.Question = Question;

}).call(this);
